trigger:
  - main

pool:
  name: Default
  demands:
    - agent.name -equals HARSH
    - Agent.Version -gtVersion 4.255.0

steps:
- checkout: self

# ✅ Set JAVA_HOME manually BEFORE Maven task
- script: |
    echo "Setting JAVA_HOME manually"
    set JAVA_HOME=C:\Program Files\Java\jdk-17
    echo JAVA_HOME is %JAVA_HOME%
  displayName: 'Set JAVA_HOME'

# ✅ Run Maven using PATH option instead of environment variable
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\\Program Files\\Java\\jdk-17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false

- task: PublishTestResults@2
  inputs: 
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'JUnit test results'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target'
    ArtifactName: 'MyArtifact'
    publishLocation: 'Container'
